export default {
  hello: 'world'
}

// "workbench.colorCustomizations": {
//   "editor.background": "#0c0c1f",
//   "sideBar.background": "#0a0a1a",
//   "sideBarSectionHeader.background": "#080813",
//   "sideBarTitle.foreground": "#9e9edf",
//   "sideBar.foreground": "#474775",
//   "gitDecoration.ignoredResourceForeground": "#47477577",
//   "gitDecoration.modifiedResourceForeground": "#4b4bd6",
//   "tree.indentGuidesStroke": "#262646",
//   "list.activeSelectionForeground": "#9e9edf",
//   "list.inactiveSelectionForeground": "#9e9edf",
//   "activityBar.background": "#0a0a1a",
//   "activityBar.activeBorder": "#333362",
//   "activityBarBadge.background": "#9e9edf",
//   "breadcrumb.background": "#0c0c1f",
//   "breadcrumb.foreground": "#2a2a49",
//   "editorGroupHeader.tabsBackground": "#0c0c1f",
//   "tab.inactiveBackground": "#0c0c1f",
//   "tab.activeBackground": "#0c0c1f",
//   "tab.activeBorder": "#333362",
//   "tab.activeForeground": "#9e9edf",
//   "tab.inactiveForeground": "#333362",
//   "titleBar.activeBackground": "#0c0c1f",
//   "panel.background": "#0a0a1a",
//   "panelTitle.activeForeground": "#9e9edf",
//   "panelTitle.activeBorder": "#333362",
//   "terminal.foreground": "#9e9edf",
//   "statusBar.background": "#0c0c1f",
//   "statusBar.foreground": "#333362",
//   "editorLineNumber.foreground": "#1c1c3aaa",
//   "editorLineNumber.activeForeground": "#373777",
//   "editor.foreground": "#9e9edf",
// },
// "editor.tokenColorCustomizations": {
//   "variables": "#aab4ec",
//   "keywords": "#9393f3",
//   "functions": "#87acfb",
//   "strings": "#bee4a5",
//   "comments": "#333362",
//   "types": "#ffef94dc",
//   "numbers": "#f8f79b",
// },